version: '3'

# args:
#   - JIRA_VERSION=${JIRA_VERSION:-8.19.0}  # 无值时用8.19.0
networks:
  bridge:
    driver: bridge

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_LOG_CONSOLE=true
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=jira
      - MYSQL_USER=jira
      - MYSQL_PASSWORD=123456
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_bin', '--lower_case_table_names=1']
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports: 
      - 3306:3306
    networks:
      - bridge
    restart: always
  jira:
    image: yeclimeric/jira:${JIRA_VERSION:-latest}
    container_name: jira
    build:
      context: .
      dockerfile: jira/Dockerfile
      args:
        - JIRA_VERSION=${JIRA_VERSION}
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./jira/conf/server.xml:/opt/atlassian/jira/conf/server.xml
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - bridge
    restart: always
  bitbucket:
    image: yeclimeric/bitbucket:${BITBUCKET_VERSION:-latest}
    container_name: bitbucket
    build:
      context: .
      dockerfile: bitbucket/Dockerfile
      args:
        - BITBUCKET_VERSION=${BITBUCKET_VERSION}
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "7990:7990"
      - "7999:7999"
    depends_on:
      - mysql
    networks:
      - bridge
    restart: always
